del Release_Build\*.obj
del Release_Build\*.tds
del Release_Build\*.exe
del Release_Build\*.pch
del Release_Build\*.map
del Release_Build\*.ilc
del Release_Build\*.ild
del Release_Build\*.ilf
del Release_Build\*.ils
del Release_Build\*.o
del Release_Build\*.d
del Debug_Build\*.obj
del Debug_Build\*.tds
del Debug_Build\*.exe
del Bebug_Build\*.pch
del Bebug_Build\*.map
del Bebug_Build\*.ilc
del Bebug_Build\*.ild
del Bebug_Build\*.ilf
del Bebug_Build\*.ils
del Bebug_Build\*.o
del Bebug_Build\*.d
