del Win32\Release\*.obj
del Win32\Release\*.tds
del Win32\Release\*.exe
del Win32\Release\*.il*
del Win32\Release\*.map
del Win32\Release\*.ini
del Win32\Release\*.o
del Win32\Release\*.d
del Win32\Debug\*.obj
del Win32\Debug\*.tds
del Win32\Debug\*.exe
del Win32\Debug\*.il*
del Win32\Debug\*.map
del Win32\Debug\*.ini
del Win32\Debug\*.o
del Win32\Debug\*.d
