
DEFINES += _RTLDLL NO_STRICT TRACE ENAGLO ENAQZS ENAGAL ENACMP ENAIRN NFREQ=3 NEXOBS=3 EXTLEX

win32{
  DEFINES += WIN32
}

# save root directory
PROJECT_ROOT_DIRECTORY = $$PWD
PROJECT_OUTPUT_DIRECTORY = $$OUT_PWD
