del Release\*.obj
del Release\*.tds
del Release\*.exe
del Release\*.il*
del Release\*.map
del Release\*.ini
del Debug\*.obj
del Debug\*.tds
del Debug\*.exe
del Debug\*.il*
del Debug\*.map
del Debug\*.ini
