del Release_Build\*.obj
del Release_Build\*.tds
del Release_Build\*.exe
del Release_Build\*.il*
del Release_Build\*.map
del Release_Build\*.ini
del Debug_Build\*.obj
del Debug_Build\*.tds
del Debug_Build\*.exe
del Debug_Build\*.il*
del Debug_Build\*.map
del Debug_Build\*.ini
