del Release\*.obj
del Release\*.exe
del Release\*.res
del Release\*.manifest
del Release\*.pdb
del Release\*.idb
del Release\*.ilk
del Release\*.dep
del Release\*.htm
del Debug\*.obj
del Debug\*.exe
del Debug\*.res
del Debug\*.manifest
del Debug\*.pdb
del Debug\*.idb
del Debug\*.ilk
del Debug\*.dep
del Debug\*.htm
del *.ncb
